.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. marsbux_qt test_marsbux_qt
clean: FORCE
	$(MAKE) -C .. marsbux_qt_clean test_marsbux_qt_clean
check: FORCE
	$(MAKE) -C .. test_marsbux_qt_check
marsbux-qt marsbux-qt.exe: FORCE
	 $(MAKE) -C .. marsbux_qt
