dist_man1_MANS=

if BUILD_marsbuxD
  dist_man1_MANS+=marsbuxd.1
endif

if ENABLE_QT
  dist_man1_MANS+=marsbux-qt.1
endif

if BUILD_marsbux_CLI
  dist_man1_MANS+=marsbux-cli.1
endif

if BUILD_marsbux_TX
  dist_man1_MANS+=marsbux-tx.1
endif

if ENABLE_WALLET
if BUILD_marsbux_WALLET
  dist_man1_MANS+=marsbux-wallet.1
endif
endif
