#!/usr/bin/env bash
#
#  marsbuxd The marsbux core server.
#
#
# chkconfig: 345 80 20
# description: marsbuxd
# processname: marsbuxd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/marsbuxd, see below
if [ -f /etc/sysconfig/marsbuxd ]; then
        . /etc/sysconfig/marsbuxd
fi

RETVAL=0

prog=marsbuxd
# you can override the lockfile via marsbuxD_LOCKFILE in /etc/sysconfig/marsbuxd
lockfile=${marsbuxD_LOCKFILE-/var/lock/subsys/marsbuxd}

# marsbuxd defaults to /usr/bin/marsbuxd, override with marsbuxD_BIN
marsbuxd=${marsbuxD_BIN-/usr/bin/marsbuxd}

# marsbuxd opts default to -disablewallet, override with marsbuxD_OPTS
marsbuxd_opts=${marsbuxD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $marsbuxd $marsbuxd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
